szTheory/exifcleaner

README.md
src/main/dock.ts
src/main/init.ts
src/renderer/select_files.ts

Adds https://github.com/szTheory/exifcleaner/issues/34

Feature - Add progress bar

---

.resources/strings.json

Update strings.json (add Japanese translation)

---

.resources/strings.json

As asked [here](https://github.com/szTheory/exifcleaner/issues/59#issuecomment-658508781) I create PR with Polish translation.

Update strings.json (add Polish translation).

---

.resources/strings.json

Added locale "es" to the strings.json file.

Added Spanish translation to strings.json

---

.resources/strings.json

german translation added ;) 
have fun and please check my issue https://github.com/szTheory/exifcleaner/issues/86
It will be very nice when you add the option to remove the source.

German translation

---

.resources/strings.json

added enhancements from https://github.com/szTheory/exifcleaner/pull/87#pullrequestreview-499234380

German translation tweaks

---

update_exiftool.pl

I was with problems to build from source in Debian 10 and Slackware 14.2. Adjusted the file.

Adjusted update_exiftool.pl to make the directories.

---

package.json
src/common/binaries.ts
src/common/i18n.ts
src/common/resources.ts
src/main/i18n.ts

Fixes https://github.com/szTheory/exifcleaner/issues/90

Simplify resource path logic between dev and prod

---

src/common/resources.ts

Fix found here https://github.com/electron-userland/electron-builder/issues/2269 and here https://github.com/NicolasConstant/sengi/issues/324

Linux app icon fix for .deb and AppImage

---

package.json

Fixes https://github.com/szTheory/exifcleaner/issues/32

.deb app icon fix

---

.resources/strings.json

Added Slovak translations to strings.json, hope its ok.

Added Slovak translations to strings.json

---

.resources/strings.json

Revised a couple sentences and fixed a typo in "Abri arquivos".

Fixed pt-BR translation

---

.resources/strings.json

Greetings from the Netherlands!

Dutch Translation added to strings.json

---

.resources/strings.json

After you merge it, i read the translation again i found a typo and one better word came to mind.
Sorry about that.

Improving the Arabic language

---

.resources/strings.json
README.md

Added the Italian language to strings.json as in #125

feat(lang): Added Italian language

---

.resources/strings.json

Add Chinese translation

---

CHANGELOG.md
package.json

[Related issue](https://github.com/szTheory/exifcleaner/issues/107)
References:
- https://www.electron.build/configuration/nsis#portable
- https://stackoverflow.com/a/50906309

Start adding Windows portable release target

---

.resources/strings.json

- polish translation of usertasks `label` and `description` (`strings.json` update),
- sorted list of translation entries.

Polish translation of usertasks. Update of strings.json.

---

README.md

Hi, this is a small pull request to link account tags to their profiles. In addition to this, I also modified my personal link as I recently renamed my account.
NOTE: Some accounts doesn't exist anymore, so I didn't put a link for them

new: Linked tags to their GitHub accounts

---

.resources/strings.json

Made by me
cus i was bored at school

Swedish Translation

---

update_exiftool.pl

update_exiftool.pl --cache-downloads-working-dir option for faster CI

---

.gitignore
.prettierrc

Should fix the first problem in #174

fix: Made Prettier use tabs instead of spaces to format files

---

.resources/strings.json

Added Czech translations
